const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const categoryRouter = require('./categoryRouter')
const productRouter = require('./productRouter')
const cartRouter = require('./cartRouter')
const messageRouter = require('./messageRouter')
const colorRouter = require('./colorRouter')
const imageRouter = require('./imageRouter')
const orderRouter = require('./orderRouter')

router.use('/user', userRouter)
router.use('/category', categoryRouter)
router.use('/product', productRouter)
router.use('/cart', cartRouter)
router.use('/message', messageRouter)
router.use('/color', colorRouter)
router.use('/image', imageRouter)
router.use('/order', orderRouter)

module.exports = router